version: '3'

services: 
  frontend_thealfastore:
    container_name: frontend-thealfastore
    image: frontend-thealfastore
    build: 
      context: .
    ports:
      - "80:3000"
    environment: 
      - VITE_API_URL=https://www.thealfa.store:3000
