version: '3'

services: 
  frontend_thealfastore:
    container_name: frontend-thealfastore
    image: frontend-thealfastore
    build: 
      context: .
    ports:
      - "3001:3001"
    environment: 
      - VITE_API_URL=https://api.thealfa.store
